export const seedDatabase = {
  users: [
    {
      id: 'usr-customer-1',
      role: 'customer',
      name: 'Sai Kiran',
      phone: '+91 91234 00001',
      email: 'sai.kiran@example.com',
      photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80',
      editableFields: ['name', 'photoUrl', 'preferences', 'addresses'],
      favoriteWorkerIds: ['wrk-praveen', 'wrk-zoya'],
      preferences: {
        language: 'English',
        reminders: true,
        contactMode: 'Chat first',
      },
    },
    {
      id: 'usr-worker-1',
      role: 'worker',
      name: 'Praveen S',
      phone: '+91 91234 00002',
      email: 'praveen.s@example.com',
      photoUrl: 'https://images.unsplash.com/photo-1615109398623-88346a601842?auto=format&fit=crop&w=240&q=80',
    },
    {
      id: 'usr-admin-1',
      role: 'admin',
      name: 'Workven Ops',
      phone: '+91 91234 00003',
      email: 'ops@workven.example',
      photoUrl: '',
    },
  ],
  services: [
    {
      id: 'srv-ac',
      name: 'AC repair',
      category: 'AC',
      icon: 'AC',
      description: 'Cooling checks, water leakage, gas refill, installation and service.',
      baseLabor: 760,
      inspectionFee: 249,
      materialHint: 520,
      warrantyDays: 10,
      eta: '60-90 min',
      popular: true,
      issues: ['Cooling is low', 'Water leakage from indoor unit', 'AC making noise', 'General cleaning service'],
    },
    {
      id: 'srv-electrical',
      name: 'Electrical repair',
      category: 'Electrical',
      icon: 'EL',
      description: 'Wiring, switches, lights, MCB trips, inverter checks and fan repair.',
      baseLabor: 420,
      inspectionFee: 149,
      materialHint: 180,
      warrantyDays: 3,
      eta: '35-55 min',
      popular: true,
      issues: ['Switch board sparking', 'Fan not rotating', 'Tube light replacement', 'MCB keeps tripping'],
    },
    {
      id: 'srv-plumbing',
      name: 'Plumbing',
      category: 'Plumbing',
      icon: 'PL',
      description: 'Leak repair, tap fitting, flush tank, drainage and pipe joint issues.',
      baseLabor: 380,
      inspectionFee: 149,
      materialHint: 220,
      warrantyDays: 7,
      eta: '30-50 min',
      popular: true,
      issues: ['Kitchen tap leakage', 'Wash basin choke', 'Flush tank issue', 'Pipe joint water drip'],
    },
    {
      id: 'srv-fan',
      name: 'Fan repair',
      category: 'Electrical',
      icon: 'FN',
      description: 'Fan installation, regulator replacement, noise checks and motor diagnosis.',
      baseLabor: 360,
      inspectionFee: 129,
      materialHint: 160,
      warrantyDays: 3,
      eta: '30-50 min',
      popular: true,
      issues: ['Fan not rotating', 'Fan speed is low', 'Fan making noise', 'New fan installation'],
    },
    {
      id: 'srv-appliance',
      name: 'Appliance repair',
      category: 'Appliance',
      icon: 'AP',
      description: 'Fridge, washing machine, microwave, chimney and geyser support.',
      baseLabor: 640,
      inspectionFee: 199,
      materialHint: 420,
      warrantyDays: 7,
      eta: '45-80 min',
      popular: true,
      issues: ['Washing machine drum issue', 'Refrigerator cooling check', 'Microwave not heating', 'Geyser inspection'],
    },
    {
      id: 'srv-carpenter',
      name: 'Carpenter',
      category: 'Carpentry',
      icon: 'CP',
      description: 'Door alignment, locks, shelves, hinges, wardrobes and fittings.',
      baseLabor: 520,
      inspectionFee: 199,
      materialHint: 260,
      warrantyDays: 15,
      eta: '45-75 min',
      popular: true,
      issues: ['Cupboard hinge loose', 'Main door alignment issue', 'Shelf mounting', 'Lock installation'],
    },
  ],
  locations: [
    {
      id: 'loc-home',
      userId: 'usr-customer-1',
      label: 'Home',
      address: 'Flat 302, Sri Heights, Kondapur, Hyderabad',
      city: 'Hyderabad',
      lat: 17.463,
      lng: 78.364,
      isDefault: true,
    },
    {
      id: 'loc-office',
      userId: 'usr-customer-1',
      label: 'Office',
      address: 'Skyline Tech Park, Hitech City, Hyderabad',
      city: 'Hyderabad',
      lat: 17.448,
      lng: 78.381,
      isDefault: false,
    },
  ],
  workers: [
    {
      id: 'wrk-praveen',
      userId: 'usr-worker-1',
      name: 'Praveen S',
      photoUrl: 'https://images.unsplash.com/photo-1615109398623-88346a601842?auto=format&fit=crop&w=240&q=80',
      skillCategories: ['Electrical', 'Fan repair'],
      primarySkill: 'Electrical',
      education: 'Diploma in Electrical Maintenance',
      experience: '6 years in apartment electrical maintenance and safety inspection.',
      previousWork: 'Former apartment maintenance supervisor. Recent work: MCB trips, switchboards, fan installation.',
      rating: 4.8,
      completedJobs: 512,
      responseTimeMins: 8,
      completionRate: 97,
      availability: 'Available now',
      status: 'approved',
      location: { lat: 17.455, lng: 78.371, locality: 'Hitech City' },
      verification: {
        education: { status: 'verified', score: 92 },
        experience: { status: 'verified', score: 90 },
        previousWork: { status: 'verified', score: 91 },
      },
      ratingScore: 88,
      badges: ['Best verified match', 'Fast responder', 'Top rated'],
    },
    {
      id: 'wrk-zoya',
      userId: 'usr-worker-2',
      name: 'Zoya Shaik',
      photoUrl: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?auto=format&fit=crop&w=240&q=80',
      skillCategories: ['AC', 'Appliance'],
      primarySkill: 'AC',
      education: 'Trade Certificate in HVAC Service',
      experience: '5 years handling split AC service, leak repair and seasonal maintenance.',
      previousWork: 'Seasonal AC service lead at CoolAir. Recent work: AC service, water leakage, cooling issue inspection.',
      rating: 4.7,
      completedJobs: 388,
      responseTimeMins: 12,
      completionRate: 95,
      availability: 'Available today',
      status: 'approved',
      location: { lat: 17.432, lng: 78.377, locality: 'Gachibowli' },
      verification: {
        education: { status: 'verified', score: 88 },
        experience: { status: 'verified', score: 86 },
        previousWork: { status: 'verified', score: 84 },
      },
      ratingScore: 86,
      badges: ['Verified', 'Experienced'],
    },
    {
      id: 'wrk-ramesh',
      userId: 'usr-worker-3',
      name: 'Ramesh Kumar',
      photoUrl: 'https://images.unsplash.com/photo-1607346256330-dee7af15f7c5?auto=format&fit=crop&w=240&q=80',
      skillCategories: ['Plumbing'],
      primarySkill: 'Plumbing',
      education: 'ITI Plumbing and Pipe Fitting',
      experience: '8 years across leak repair, bathroom fittings and drainage diagnosis.',
      previousWork: '6 years with MetroCare Facility Services. Recent work: kitchen tap replacement, basin choke repair.',
      rating: 4.9,
      completedJobs: 641,
      responseTimeMins: 10,
      completionRate: 98,
      availability: 'Available now',
      status: 'approved',
      location: { lat: 17.466, lng: 78.359, locality: 'Kondapur' },
      verification: {
        education: { status: 'verified', score: 96 },
        experience: { status: 'verified', score: 95 },
        previousWork: { status: 'verified', score: 95 },
      },
      ratingScore: 93,
      badges: ['Best verified match', 'Experienced', 'Top rated'],
    },
    {
      id: 'wrk-fatima',
      userId: 'usr-worker-4',
      name: 'Fatima Noor',
      photoUrl: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=240&q=80',
      skillCategories: ['Appliance'],
      primarySkill: 'Appliance',
      education: 'Home Appliance Repair Certificate',
      experience: '4 years at a kitchen appliance service center.',
      previousWork: 'Recent work: washing machine, microwave, chimney cleaning and geyser support.',
      rating: 4.8,
      completedJobs: 255,
      responseTimeMins: 14,
      completionRate: 94,
      availability: 'Available today',
      status: 'approved',
      location: { lat: 17.438, lng: 78.399, locality: 'Madhapur' },
      verification: {
        education: { status: 'verified', score: 85 },
        experience: { status: 'verified', score: 82 },
        previousWork: { status: 'verified', score: 80 },
      },
      ratingScore: 85,
      badges: ['Verified', 'Fast responder'],
    },
    {
      id: 'wrk-manohar',
      userId: 'usr-worker-5',
      name: 'Manohar B',
      photoUrl: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?auto=format&fit=crop&w=240&q=80',
      skillCategories: ['Carpentry'],
      primarySkill: 'Carpentry',
      education: 'Furniture Making Course',
      experience: '7 years in wardrobes, hinges, locks, shelves and door alignment.',
      previousWork: 'Wardrobe installation contractor. Recent work: door alignment, shelf mounting, lock installation.',
      rating: 4.6,
      completedJobs: 302,
      responseTimeMins: 16,
      completionRate: 93,
      availability: 'Next slot',
      status: 'pending_review',
      location: { lat: 17.483, lng: 78.392, locality: 'Miyapur' },
      verification: {
        education: { status: 'verified', score: 80 },
        experience: { status: 'verified', score: 88 },
        previousWork: { status: 'pending', score: 72 },
      },
      ratingScore: 78,
      badges: ['Verification review', 'Experienced'],
    },
  ],
  bookings: [
    {
      id: 'bkg-24081',
      invoiceNumber: 'INV-WV-24081',
      customerId: 'usr-customer-1',
      workerId: 'wrk-ramesh',
      serviceId: 'srv-plumbing',
      serviceName: 'Plumbing',
      issue: 'Kitchen tap leakage',
      status: 'Completed',
      slot: '12 May 2026, 4:30 PM',
      address: 'Flat 302, Sri Heights, Kondapur, Hyderabad',
      estimateTotal: 1240,
      finalTotal: 1180,
      platformFee: 59,
      workerPayout: 1121,
      paymentStatus: 'Paid',
      paymentMode: 'Online',
      warrantyDays: 7,
      createdAt: '2026-05-12T10:00:00.000Z',
      lineItems: [
        { label: 'Inspection and visit', amount: 149 },
        { label: 'Tap cartridge', amount: 680 },
        { label: 'Service labor', amount: 351 },
      ],
      tracking: { progress: 100, currentStep: 'Completed' },
      summary: 'Replaced cartridge, tightened joint and tested water pressure.',
    },
    {
      id: 'bkg-24092',
      invoiceNumber: 'INV-WV-24092',
      customerId: 'usr-customer-1',
      workerId: 'wrk-zoya',
      serviceId: 'srv-ac',
      serviceName: 'AC repair',
      issue: 'General cleaning service',
      status: 'Scheduled',
      slot: 'Today, 6:00 PM',
      address: 'Skyline Tech Park, Hitech City, Hyderabad',
      estimateTotal: 1410,
      finalTotal: null,
      platformFee: 0,
      workerPayout: 0,
      paymentStatus: 'Pending',
      paymentMode: 'Cash after service',
      warrantyDays: 10,
      createdAt: '2026-05-26T12:00:00.000Z',
      lineItems: [
        { label: 'Inspection and visit', amount: 249 },
        { label: 'Service labor', amount: 623 },
        { label: 'Consumables estimate', amount: 286 },
        { label: 'Travel and slot fee', amount: 252 },
      ],
      tracking: { progress: 25, currentStep: 'Worker assigned' },
      summary: 'Scheduled for inspection.',
    },
  ],
  workerRequests: [
    {
      id: 'job-7102',
      serviceId: 'srv-electrical',
      serviceName: 'Electrical repair',
      issue: 'Light fitting repair',
      customerId: 'usr-customer-1',
      customerName: 'Ananya Rao',
      workerId: 'wrk-praveen',
      address: 'Plot 18, Ayyappa Society, Madhapur, Hyderabad',
      distanceKm: 2.1,
      slot: 'Today, 5:15 PM',
      status: 'New request',
      difficulty: 'Small',
      estimateTotal: 820,
      paymentMode: 'Online',
      proofPhotos: [],
    },
    {
      id: 'job-7103',
      serviceId: 'srv-plumbing',
      serviceName: 'Plumbing',
      issue: 'Wash basin choke',
      customerId: 'usr-customer-2',
      customerName: 'Siva Ch',
      workerId: 'wrk-ramesh',
      address: 'Green Valley Apartments, Kondapur, Hyderabad',
      distanceKm: 3.5,
      slot: 'Within 45 minutes',
      status: 'Accepted',
      difficulty: 'Small',
      estimateTotal: 760,
      paymentMode: 'Cash after service',
      proofPhotos: [],
    },
  ],
  complaints: [
    {
      id: 'cmp-1821',
      bookingId: 'bkg-24081',
      customerId: 'usr-customer-1',
      workerId: 'wrk-ramesh',
      reason: 'Leak returned within warranty',
      status: 'Refund review',
      refundStatus: 'Under review',
      requestedRefund: 280,
      createdAt: '2026-05-18T11:00:00.000Z',
    },
  ],
  reviews: [
    {
      id: 'rev-1001',
      bookingId: 'bkg-24081',
      customerId: 'usr-customer-1',
      workerId: 'wrk-ramesh',
      rating: 5,
      feedback: 'Clear explanation and clean repair.',
      createdAt: '2026-05-12T15:00:00.000Z',
    },
  ],
  payments: [
    {
      id: 'pay-24081',
      bookingId: 'bkg-24081',
      amount: 1180,
      status: 'Paid',
      method: 'Online',
      capturedAt: '2026-05-12T14:30:00.000Z',
    },
  ],
  notifications: [
    {
      id: 'ntf-1',
      userId: 'usr-customer-1',
      title: 'AC service reminder',
      body: 'Your next AC cleaning reminder is due this weekend.',
      read: false,
      createdAt: '2026-05-26T08:00:00.000Z',
    },
  ],
  supportTickets: [
    {
      id: 'tic-1001',
      customerId: 'usr-customer-1',
      subject: 'Invoice clarification',
      status: 'Open',
      priority: 'Medium',
      owner: 'Admin support',
    },
  ],
  settings: {
    commissionPercent: 5,
    emergencyFee: 120,
    cancellationWindowMins: 30,
    rankingWeights: {
      education: 0.18,
      experience: 0.2,
      previousWork: 0.2,
      rating: 0.17,
      distance: 0.15,
      completionRate: 0.1,
    },
  },
  otpChallenges: [],
  auditAlerts: [],
}
