export const serviceCategories = [
  {
    name: 'Electrical',
    shortLabel: 'EL',
    blurb: 'Switch boards, fans, lights, MCB trips, inverter checks',
    eta: '45 mins',
  },
  {
    name: 'Plumbing',
    shortLabel: 'PL',
    blurb: 'Tap leaks, pipe blocks, flush issues, drain cleaning',
    eta: '38 mins',
  },
  {
    name: 'AC',
    shortLabel: 'AC',
    blurb: 'Cooling, water leakage, gas top-up, seasonal servicing',
    eta: '70 mins',
  },
  {
    name: 'Carpentry',
    shortLabel: 'CP',
    blurb: 'Door locks, hinges, shelves, wardrobes and fittings',
    eta: '55 mins',
  },
  {
    name: 'Appliance',
    shortLabel: 'AP',
    blurb: 'Fridge, washing machine, microwave and kitchen help',
    eta: '50 mins',
  },
  {
    name: 'Painting',
    shortLabel: 'PT',
    blurb: 'Touch-up work, patch repair, wall damage and prep',
    eta: '90 mins',
  },
]

export const serviceSuggestions = [
  'Electrical repair',
  'Electric switch replacement',
  'Fan installation',
  'Light fitting repair',
  'MCB trip inspection',
  'Plumbing leak repair',
  'Tap replacement',
  'Bathroom blockage cleanup',
  'Sink pipe repair',
  'AC cooling issue',
  'AC gas refill',
  'AC general service',
  'Carpenter for cupboard repair',
  'Door lock fixing',
  'Washing machine inspection',
  'Refrigerator service',
  'Wall patch painting',
  'Geyser installation',
]

export const repairCatalog = {
  Electrical: [
    'Switch board sparking',
    'Fan not rotating',
    'Tube light replacement',
    'MCB keeps tripping',
    'Inverter backup issue',
    'Door bell not working',
    'Exhaust fan repair',
    'Power socket installation',
  ],
  Plumbing: [
    'Kitchen tap leakage',
    'Wash basin choke',
    'Flush tank issue',
    'Shower pressure low',
    'Pipe joint water drip',
    'Motor line valve issue',
    'Drain smell inspection',
    'Geyser outlet leakage',
  ],
  AC: [
    'Cooling is low',
    'Water leakage from indoor unit',
    'AC making noise',
    'General cleaning service',
    'Remote or sensor issue',
    'Gas refill inspection',
  ],
  Carpentry: [
    'Cupboard hinge loose',
    'Main door alignment issue',
    'Shelf mounting',
    'Drawer channel repair',
    'Lock installation',
  ],
  Appliance: [
    'Washing machine drum issue',
    'Refrigerator cooling check',
    'Microwave not heating',
    'RO stand fitting',
    'Chimney cleaning request',
  ],
  Painting: [
    'Single wall touch-up',
    'Water damage patch repair',
    'Corner crack filling',
    'Ceiling stain repaint',
    'Rental move-out paint fix',
  ],
}

export const arrivalSlots = [
  {
    id: 'asap',
    label: 'Within 45 minutes',
    caption: 'Fastest available expert',
  },
  {
    id: 'today-evening',
    label: 'Today, 6:00 PM',
    caption: 'Best for after-office visits',
  },
  {
    id: 'tomorrow-morning',
    label: 'Tomorrow, 10:30 AM',
    caption: 'Planned visit with reminder',
  },
  {
    id: 'weekend',
    label: 'Saturday, 11:00 AM',
    caption: 'Weekend repair window',
  },
]

export const indianLanguages = [
  'English',
  'Hindi',
  'Telugu',
  'Tamil',
  'Kannada',
  'Malayalam',
  'Marathi',
  'Bengali',
  'Gujarati',
  'Punjabi',
  'Odia',
  'Urdu',
  'Assamese',
  'Konkani',
]

export const initialLocations = [
  {
    id: 'loc-home',
    label: 'Home',
    address: 'Flat 302, Sri Heights, Kondapur, Hyderabad',
    city: 'Hyderabad',
    distanceKm: 1.8,
  },
  {
    id: 'loc-office',
    label: 'Office',
    address: 'Skyline Tech Park, Hitech City, Hyderabad',
    city: 'Hyderabad',
    distanceKm: 7.4,
  },
  {
    id: 'loc-parents',
    label: 'Parents',
    address: 'Beach Road, MVP Colony, Visakhapatnam',
    city: 'Visakhapatnam',
    distanceKm: 620,
  },
]

export const initialOrders = [
  {
    id: 'WV-24081',
    invoiceNumber: 'INV-WV-24081',
    service: 'Plumbing',
    issue: 'Kitchen tap leakage',
    status: 'Completed',
    arrivalWindow: '12 May 2026, 4:30 PM',
    workerName: 'Ramesh Kumar',
    address: 'Flat 302, Sri Heights, Kondapur, Hyderabad',
    total: '₹1,240',
    lineItems: [
      { label: 'Visit charge', amount: '₹199' },
      { label: 'Tap cartridge replacement', amount: '₹690' },
      { label: 'Service labour', amount: '₹351' },
    ],
  },
  {
    id: 'WV-23992',
    invoiceNumber: 'INV-WV-23992',
    service: 'AC',
    issue: 'AC general service',
    status: 'Scheduled',
    arrivalWindow: '19 May 2026, 10:30 AM',
    workerName: 'Auto assigning',
    address: 'Skyline Tech Park, Hitech City, Hyderabad',
    total: 'Estimate after inspection',
    lineItems: [{ label: 'Inspection slot', amount: '₹249' }],
  },
  {
    id: 'WV-23844',
    invoiceNumber: 'INV-WV-23844',
    service: 'Electrical',
    issue: 'MCB keeps tripping',
    status: 'Completed',
    arrivalWindow: '03 May 2026, 7:15 PM',
    workerName: 'Praveen S',
    address: 'Flat 302, Sri Heights, Kondapur, Hyderabad',
    total: '₹980',
    lineItems: [
      { label: 'Visit charge', amount: '₹199' },
      { label: 'MCB unit', amount: '₹430' },
      { label: 'Installation labour', amount: '₹351' },
    ],
  },
]

export const partnerJobTemplates = [
  {
    id: 'JOB-7102',
    service: 'Electrical',
    issue: 'Light fitting repair',
    customerName: 'Ananya Rao',
    locationLabel: 'Madhapur',
    address: 'Plot 18, Ayyappa Society, Madhapur, Hyderabad',
    distanceKm: 2.1,
    arrivalWindow: 'Today, 5:15 PM',
    priority: 'Nearby first',
    status: 'New',
  },
  {
    id: 'JOB-7103',
    service: 'Plumbing',
    issue: 'Wash basin choke',
    customerName: 'Siva Ch',
    locationLabel: 'Kondapur',
    address: 'Green Valley Apartments, Kondapur, Hyderabad',
    distanceKm: 3.5,
    arrivalWindow: 'Within 45 minutes',
    priority: 'Nearby first',
    status: 'New',
  },
  {
    id: 'JOB-7104',
    service: 'AC',
    issue: 'Cooling is low',
    customerName: 'Mubeen Khan',
    locationLabel: 'Gachibowli',
    address: 'Hill Ridge Villas, Gachibowli, Hyderabad',
    distanceKm: 5.8,
    arrivalWindow: 'Today, 7:00 PM',
    priority: 'Nearby first',
    status: 'New',
  },
  {
    id: 'JOB-7105',
    service: 'Electrical',
    issue: 'Fan not rotating',
    customerName: 'Deepa Nair',
    locationLabel: 'Miyapur',
    address: 'Pragathi Nagar Main Road, Miyapur, Hyderabad',
    distanceKm: 12.4,
    arrivalWindow: 'Tomorrow, 10:30 AM',
    priority: 'Next circle',
    status: 'New',
  },
  {
    id: 'JOB-7106',
    service: 'Plumbing',
    issue: 'Pipe joint water drip',
    customerName: 'Ritu Sharma',
    locationLabel: 'Kukatpally',
    address: 'Vasantha Nagar, Kukatpally, Hyderabad',
    distanceKm: 14.1,
    arrivalWindow: 'Saturday, 11:00 AM',
    priority: 'Next circle',
    status: 'New',
  },
]
