export const serviceCategories = [
  {
    name: 'Electrical',
    shortLabel: 'EL',
    blurb: 'Wiring, fans, lights, switch boards, MCB trips and inverter checks.',
    eta: '35-55 min',
    baseLabor: 420,
    inspectionFee: 149,
    materialHint: 180,
    warrantyDays: 3,
  },
  {
    name: 'Plumbing',
    shortLabel: 'PL',
    blurb: 'Leak repair, tap fitting, flush tank, drainage and pipe joint issues.',
    eta: '30-50 min',
    baseLabor: 380,
    inspectionFee: 149,
    materialHint: 220,
    warrantyDays: 7,
  },
  {
    name: 'AC',
    shortLabel: 'AC',
    blurb: 'Cooling checks, water leakage, gas refill, installation and servicing.',
    eta: '60-90 min',
    baseLabor: 760,
    inspectionFee: 249,
    materialHint: 520,
    warrantyDays: 10,
  },
  {
    name: 'Carpentry',
    shortLabel: 'CP',
    blurb: 'Door alignment, locks, shelves, hinges, wardrobes and fittings.',
    eta: '45-75 min',
    baseLabor: 520,
    inspectionFee: 199,
    materialHint: 260,
    warrantyDays: 15,
  },
  {
    name: 'Appliance',
    shortLabel: 'AP',
    blurb: 'Fridge, washing machine, microwave, chimney and geyser support.',
    eta: '45-80 min',
    baseLabor: 640,
    inspectionFee: 199,
    materialHint: 420,
    warrantyDays: 7,
  },
  {
    name: 'Painting',
    shortLabel: 'PT',
    blurb: 'Patch repair, rental touch-ups, stain cover, crack filling and prep.',
    eta: '80-120 min',
    baseLabor: 700,
    inspectionFee: 199,
    materialHint: 380,
    warrantyDays: 15,
  },
]

export const serviceSuggestions = [
  'Electrical repair',
  'Electric switch replacement',
  'Fan installation',
  'Light fitting repair',
  'MCB trip inspection',
  'Plumbing leak repair',
  'Tap replacement',
  'Bathroom blockage cleanup',
  'Sink pipe repair',
  'AC cooling issue',
  'AC gas refill',
  'AC general service',
  'Carpenter for cupboard repair',
  'Door lock fixing',
  'Washing machine inspection',
  'Refrigerator service',
  'Wall patch painting',
  'Geyser installation',
]

export const repairCatalog = {
  Electrical: [
    'Switch board sparking',
    'Fan not rotating',
    'Tube light replacement',
    'MCB keeps tripping',
    'Inverter backup issue',
    'Door bell not working',
    'Exhaust fan repair',
    'Power socket installation',
  ],
  Plumbing: [
    'Kitchen tap leakage',
    'Wash basin choke',
    'Flush tank issue',
    'Shower pressure low',
    'Pipe joint water drip',
    'Motor line valve issue',
    'Drain smell inspection',
    'Geyser outlet leakage',
  ],
  AC: [
    'Cooling is low',
    'Water leakage from indoor unit',
    'AC making noise',
    'General cleaning service',
    'Remote or sensor issue',
    'Gas refill inspection',
  ],
  Carpentry: [
    'Cupboard hinge loose',
    'Main door alignment issue',
    'Shelf mounting',
    'Drawer channel repair',
    'Lock installation',
  ],
  Appliance: [
    'Washing machine drum issue',
    'Refrigerator cooling check',
    'Microwave not heating',
    'RO stand fitting',
    'Chimney cleaning request',
  ],
  Painting: [
    'Single wall touch-up',
    'Water damage patch repair',
    'Corner crack filling',
    'Ceiling stain repaint',
    'Rental move-out paint fix',
  ],
}

export const difficultyTags = [
  {
    id: 'small',
    label: 'Small',
    multiplier: 0.82,
    trustGate: 0,
    caption: 'Starter-safe tasks such as inspection, tightening, replacement or cleaning.',
  },
  {
    id: 'medium',
    label: 'Medium',
    multiplier: 1,
    trustGate: 58,
    caption: 'Standard repair work with moderate parts or diagnosis.',
  },
  {
    id: 'large',
    label: 'Large',
    multiplier: 1.55,
    trustGate: 78,
    caption: 'Complex repair, installation, rewiring, deep blockage or multi-step work.',
  },
]

export const materialOptions = [
  { id: 'light', label: 'Light materials', multiplier: 0.55 },
  { id: 'standard', label: 'Standard materials', multiplier: 1 },
  { id: 'heavy', label: 'More materials', multiplier: 1.65 },
]

export const arrivalSlots = [
  {
    id: 'asap',
    label: 'Within 45 minutes',
    caption: 'Book instantly with emergency-capable partners nearby.',
    urgencyFee: 120,
  },
  {
    id: 'today-evening',
    label: 'Today, 6:00 PM',
    caption: 'Best for after-office visits.',
    urgencyFee: 60,
  },
  {
    id: 'tomorrow-morning',
    label: 'Tomorrow, 10:30 AM',
    caption: 'Planned visit with reminder.',
    urgencyFee: 0,
  },
  {
    id: 'weekend',
    label: 'Saturday, 11:00 AM',
    caption: 'Weekend repair window.',
    urgencyFee: 80,
  },
]

export const indianLanguages = [
  'English',
  'Hindi',
  'Telugu',
  'Tamil',
  'Kannada',
  'Malayalam',
  'Marathi',
  'Bengali',
  'Gujarati',
  'Punjabi',
  'Odia',
  'Urdu',
  'Assamese',
  'Konkani',
]

export const initialLocations = [
  {
    id: 'loc-home',
    label: 'Home',
    address: 'Flat 302, Sri Heights, Kondapur, Hyderabad',
    city: 'Hyderabad',
    distanceKm: 1.8,
  },
  {
    id: 'loc-office',
    label: 'Office',
    address: 'Skyline Tech Park, Hitech City, Hyderabad',
    city: 'Hyderabad',
    distanceKm: 7.4,
  },
  {
    id: 'loc-parents',
    label: 'Parents',
    address: 'Beach Road, MVP Colony, Visakhapatnam',
    city: 'Visakhapatnam',
    distanceKm: 620,
  },
]

export const workerDirectory = [
  {
    id: 'wrk-ramesh',
    name: 'Ramesh Kumar',
    domain: 'Plumbing',
    rating: 4.9,
    experienceYears: 8,
    completedJobs: 641,
    distanceKm: 1.7,
    etaMins: 24,
    trustScore: 94,
    verified: true,
    qualification: 'ITI Plumbing and Pipe Fitting',
    studyScore: 96,
    documentScore: 94,
    previousWorkScore: 95,
    trialScore: 93,
    ratingScore: 93,
    backgroundCheck: 'Cleared',
    previousWork: '6 years with MetroCare Facility Services',
    badges: ['Verified', 'Experienced', 'Top rated'],
    recentWork: 'Leak repair, bathroom fittings, kitchen tap replacement',
  },
  {
    id: 'wrk-praveen',
    name: 'Praveen S',
    domain: 'Electrical',
    rating: 4.8,
    experienceYears: 6,
    completedJobs: 512,
    distanceKm: 2.3,
    etaMins: 31,
    trustScore: 91,
    verified: true,
    qualification: 'Diploma in Electrical Maintenance',
    studyScore: 92,
    documentScore: 96,
    previousWorkScore: 90,
    trialScore: 91,
    ratingScore: 88,
    backgroundCheck: 'Cleared',
    previousWork: 'Former apartment maintenance supervisor',
    badges: ['Verified', 'Fast responder', 'Top rated'],
    recentWork: 'MCB trips, switchboards, fan installation',
  },
  {
    id: 'wrk-zoya',
    name: 'Zoya Shaik',
    domain: 'AC',
    rating: 4.7,
    experienceYears: 5,
    completedJobs: 388,
    distanceKm: 4.8,
    etaMins: 46,
    trustScore: 87,
    verified: true,
    qualification: 'Trade Certificate in HVAC Service',
    studyScore: 88,
    documentScore: 91,
    previousWorkScore: 84,
    trialScore: 86,
    ratingScore: 86,
    backgroundCheck: 'Cleared',
    previousWork: 'Seasonal AC service lead at CoolAir',
    badges: ['Verified', 'Experienced'],
    recentWork: 'AC service, water leakage, cooling issue inspection',
  },
  {
    id: 'wrk-manohar',
    name: 'Manohar B',
    domain: 'Carpentry',
    rating: 4.6,
    experienceYears: 7,
    completedJobs: 302,
    distanceKm: 6.2,
    etaMins: 55,
    trustScore: 82,
    verified: true,
    qualification: 'Furniture Making Course',
    studyScore: 80,
    documentScore: 84,
    previousWorkScore: 88,
    trialScore: 80,
    ratingScore: 78,
    backgroundCheck: 'Cleared',
    previousWork: 'Wardrobe installation contractor',
    badges: ['Verified', 'Experienced'],
    recentWork: 'Door alignment, shelf mounting, lock installation',
  },
  {
    id: 'wrk-anil',
    name: 'Anil Varma',
    domain: 'Electrical',
    rating: 4.3,
    experienceYears: 1,
    completedJobs: 36,
    distanceKm: 1.1,
    etaMins: 18,
    trustScore: 56,
    verified: true,
    qualification: 'ITI Electrician trainee',
    studyScore: 72,
    documentScore: 76,
    previousWorkScore: 42,
    trialScore: 51,
    ratingScore: 39,
    backgroundCheck: 'Cleared',
    previousWork: 'Reference from local electrical store',
    badges: ['Verified', 'Trial jobs'],
    recentWork: 'Switch replacement, bell repair, light fitting',
  },
  {
    id: 'wrk-fatima',
    name: 'Fatima Noor',
    domain: 'Appliance',
    rating: 4.8,
    experienceYears: 4,
    completedJobs: 255,
    distanceKm: 3.9,
    etaMins: 40,
    trustScore: 84,
    verified: true,
    qualification: 'Home Appliance Repair Certificate',
    studyScore: 85,
    documentScore: 88,
    previousWorkScore: 80,
    trialScore: 82,
    ratingScore: 85,
    backgroundCheck: 'Cleared',
    previousWork: 'Kitchen appliance repair center',
    badges: ['Verified', 'Fast responder'],
    recentWork: 'Washing machine, microwave, chimney cleaning',
  },
  {
    id: 'wrk-naveen',
    name: 'Naveen Reddy',
    domain: 'Painting',
    rating: 4.5,
    experienceYears: 3,
    completedJobs: 144,
    distanceKm: 8.4,
    etaMins: 72,
    trustScore: 73,
    verified: true,
    qualification: 'Wall finishing course',
    studyScore: 76,
    documentScore: 78,
    previousWorkScore: 70,
    trialScore: 74,
    ratingScore: 67,
    backgroundCheck: 'Cleared',
    previousWork: 'Rental repaint crew member',
    badges: ['Verified'],
    recentWork: 'Patch painting, crack filling, ceiling stain repaint',
  },
]

export const initialOrders = [
  {
    id: 'WV-24081',
    invoiceNumber: 'INV-WV-24081',
    service: 'Plumbing',
    issue: 'Kitchen tap leakage',
    problemDescription: 'Leak from the kitchen mixer tap after closing.',
    difficulty: 'medium',
    status: 'Completed',
    arrivalWindow: '12 May 2026, 4:30 PM',
    workerId: 'wrk-ramesh',
    workerName: 'Ramesh Kumar',
    workerTrustScore: 94,
    address: 'Flat 302, Sri Heights, Kondapur, Hyderabad',
    paymentMode: 'Online',
    paymentStatus: 'Paid',
    estimateTotal: 1240,
    finalTotal: 1180,
    platformFee: 59,
    workerPayout: 1121,
    warrantyDays: 7,
    summary: 'Replaced cartridge, tightened joint and tested water pressure.',
    lineItems: [
      { label: 'Inspection and visit', amount: 149 },
      { label: 'Tap cartridge', amount: 680 },
      { label: 'Service labor', amount: 351 },
    ],
  },
  {
    id: 'WV-23992',
    invoiceNumber: 'INV-WV-23992',
    service: 'AC',
    issue: 'AC general service',
    problemDescription: 'Seasonal AC service before summer usage.',
    difficulty: 'small',
    status: 'Scheduled',
    arrivalWindow: '19 May 2026, 10:30 AM',
    workerId: 'wrk-zoya',
    workerName: 'Zoya Shaik',
    workerTrustScore: 87,
    address: 'Skyline Tech Park, Hitech City, Hyderabad',
    paymentMode: 'Cash after service',
    paymentStatus: 'Pending',
    estimateTotal: 1410,
    finalTotal: null,
    platformFee: 0,
    workerPayout: 0,
    warrantyDays: 10,
    summary: 'Scheduled for inspection.',
    lineItems: [
      { label: 'Inspection and visit', amount: 249 },
      { label: 'Service labor', amount: 623 },
      { label: 'Consumables estimate', amount: 286 },
      { label: 'Travel and slot fee', amount: 252 },
    ],
  },
  {
    id: 'WV-23844',
    invoiceNumber: 'INV-WV-23844',
    service: 'Electrical',
    issue: 'MCB keeps tripping',
    problemDescription: 'MCB trips when geyser and kitchen plug are used together.',
    difficulty: 'large',
    status: 'Completed',
    arrivalWindow: '03 May 2026, 7:15 PM',
    workerId: 'wrk-praveen',
    workerName: 'Praveen S',
    workerTrustScore: 91,
    address: 'Flat 302, Sri Heights, Kondapur, Hyderabad',
    paymentMode: 'Online',
    paymentStatus: 'Paid',
    estimateTotal: 1370,
    finalTotal: 1460,
    platformFee: 73,
    workerPayout: 1387,
    warrantyDays: 3,
    summary: 'Replaced overloaded MCB and separated loose neutral connection.',
    lineItems: [
      { label: 'Inspection and visit', amount: 149 },
      { label: 'MCB unit', amount: 430 },
      { label: 'Installation labor', amount: 651 },
      { label: 'Safety testing', amount: 230 },
    ],
  },
]

export const partnerJobTemplates = [
  {
    id: 'JOB-7102',
    service: 'Electrical',
    issue: 'Light fitting repair',
    customerName: 'Ananya Rao',
    locationLabel: 'Madhapur',
    address: 'Plot 18, Ayyappa Society, Madhapur, Hyderabad',
    distanceKm: 2.1,
    arrivalWindow: 'Today, 5:15 PM',
    priority: 'Nearby first',
    status: 'New',
    difficulty: 'small',
    estimateTotal: 820,
    paymentMode: 'Online',
  },
  {
    id: 'JOB-7103',
    service: 'Plumbing',
    issue: 'Wash basin choke',
    customerName: 'Siva Ch',
    locationLabel: 'Kondapur',
    address: 'Green Valley Apartments, Kondapur, Hyderabad',
    distanceKm: 3.5,
    arrivalWindow: 'Within 45 minutes',
    priority: 'Nearby first',
    status: 'New',
    difficulty: 'small',
    estimateTotal: 760,
    paymentMode: 'Cash after service',
  },
  {
    id: 'JOB-7104',
    service: 'AC',
    issue: 'Cooling is low',
    customerName: 'Mubeen Khan',
    locationLabel: 'Gachibowli',
    address: 'Hill Ridge Villas, Gachibowli, Hyderabad',
    distanceKm: 5.8,
    arrivalWindow: 'Today, 7:00 PM',
    priority: 'Next circle',
    status: 'New',
    difficulty: 'medium',
    estimateTotal: 1780,
    paymentMode: 'Online',
  },
  {
    id: 'JOB-7105',
    service: 'Electrical',
    issue: 'Fan not rotating',
    customerName: 'Deepa Nair',
    locationLabel: 'Miyapur',
    address: 'Pragathi Nagar Main Road, Miyapur, Hyderabad',
    distanceKm: 12.4,
    arrivalWindow: 'Tomorrow, 10:30 AM',
    priority: 'Next circle',
    status: 'New',
    difficulty: 'medium',
    estimateTotal: 1030,
    paymentMode: 'Online',
  },
  {
    id: 'JOB-7106',
    service: 'Plumbing',
    issue: 'Pipe joint water drip',
    customerName: 'Ritu Sharma',
    locationLabel: 'Kukatpally',
    address: 'Vasantha Nagar, Kukatpally, Hyderabad',
    distanceKm: 14.1,
    arrivalWindow: 'Saturday, 11:00 AM',
    priority: 'Next circle',
    status: 'New',
    difficulty: 'large',
    estimateTotal: 1680,
    paymentMode: 'Cash after service',
  },
]

export const verificationSteps = [
  'Phone OTP',
  'Government ID',
  'Certificate review',
  'Background check',
  'Skill test',
  'Starter jobs',
]

export const trustFormula = [
  { label: 'Study background', value: 20 },
  { label: 'Document verification', value: 20 },
  { label: 'Previous work', value: 20 },
  { label: 'Trial jobs', value: 20 },
  { label: 'Customer ratings', value: 20 },
]

export const adminComplaints = [
  {
    id: 'CMP-1821',
    orderId: 'WV-24081',
    customer: 'Sai Kiran',
    worker: 'Ramesh Kumar',
    reason: 'Leak returned within warranty',
    status: 'Refund review',
    requestedRefund: 280,
  },
  {
    id: 'CMP-1816',
    orderId: 'WV-23844',
    customer: 'Sai Kiran',
    worker: 'Praveen S',
    reason: 'Customer requested invoice clarification',
    status: 'Resolved',
    requestedRefund: 0,
  },
]
